// Code generated by ent, DO NOT EDIT.

package spacecraft

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the spacecraft type in the database.
	Label = "spacecraft"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldClass holds the string denoting the class field in the database.
	FieldClass = "class"
	// FieldCrew holds the string denoting the crew field in the database.
	FieldCrew = "crew"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeArmaments holds the string denoting the armaments edge name in mutations.
	EdgeArmaments = "armaments"
	// Table holds the table name of the spacecraft in the database.
	Table = "spacecrafts"
	// ArmamentsTable is the table that holds the armaments relation/edge. The primary key declared below.
	ArmamentsTable = "spacecraft_armaments"
	// ArmamentsInverseTable is the table name for the Armament entity.
	// It exists in this package in order to avoid circular dependency with the "armament" package.
	ArmamentsInverseTable = "armaments"
)

// Columns holds all SQL columns for spacecraft fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldClass,
	FieldCrew,
	FieldImage,
	FieldValue,
	FieldStatus,
}

var (
	// ArmamentsPrimaryKey and ArmamentsColumn2 are the table columns denoting the
	// primary key for the armaments relation (M2M).
	ArmamentsPrimaryKey = []string{"spacecraft_id", "armament_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Spacecraft queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByClass orders the results by the class field.
func ByClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClass, opts...).ToFunc()
}

// ByCrew orders the results by the crew field.
func ByCrew(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCrew, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByArmamentsCount orders the results by armaments count.
func ByArmamentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newArmamentsStep(), opts...)
	}
}

// ByArmaments orders the results by armaments terms.
func ByArmaments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArmamentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newArmamentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArmamentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ArmamentsTable, ArmamentsPrimaryKey...),
	)
}
