// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArmamentsColumns holds the columns for the "armaments" table.
	ArmamentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "qty", Type: field.TypeInt},
	}
	// ArmamentsTable holds the schema information for the "armaments" table.
	ArmamentsTable = &schema.Table{
		Name:       "armaments",
		Columns:    ArmamentsColumns,
		PrimaryKey: []*schema.Column{ArmamentsColumns[0]},
	}
	// SpacecraftsColumns holds the columns for the "spacecrafts" table.
	SpacecraftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "class", Type: field.TypeString},
		{Name: "crew", Type: field.TypeInt},
		{Name: "image", Type: field.TypeString},
		{Name: "value", Type: field.TypeFloat64},
		{Name: "status", Type: field.TypeString},
	}
	// SpacecraftsTable holds the schema information for the "spacecrafts" table.
	SpacecraftsTable = &schema.Table{
		Name:       "spacecrafts",
		Columns:    SpacecraftsColumns,
		PrimaryKey: []*schema.Column{SpacecraftsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// SpacecraftArmamentsColumns holds the columns for the "spacecraft_armaments" table.
	SpacecraftArmamentsColumns = []*schema.Column{
		{Name: "spacecraft_id", Type: field.TypeInt},
		{Name: "armament_id", Type: field.TypeInt},
	}
	// SpacecraftArmamentsTable holds the schema information for the "spacecraft_armaments" table.
	SpacecraftArmamentsTable = &schema.Table{
		Name:       "spacecraft_armaments",
		Columns:    SpacecraftArmamentsColumns,
		PrimaryKey: []*schema.Column{SpacecraftArmamentsColumns[0], SpacecraftArmamentsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "spacecraft_armaments_spacecraft_id",
				Columns:    []*schema.Column{SpacecraftArmamentsColumns[0]},
				RefColumns: []*schema.Column{SpacecraftsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "spacecraft_armaments_armament_id",
				Columns:    []*schema.Column{SpacecraftArmamentsColumns[1]},
				RefColumns: []*schema.Column{ArmamentsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArmamentsTable,
		SpacecraftsTable,
		UsersTable,
		SpacecraftArmamentsTable,
	}
)

func init() {
	SpacecraftArmamentsTable.ForeignKeys[0].RefTable = SpacecraftsTable
	SpacecraftArmamentsTable.ForeignKeys[1].RefTable = ArmamentsTable
}
