// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spacecraft/ent/armament"
	"spacecraft/ent/spacecraft"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArmamentCreate is the builder for creating a Armament entity.
type ArmamentCreate struct {
	config
	mutation *ArmamentMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (ac *ArmamentCreate) SetTitle(s string) *ArmamentCreate {
	ac.mutation.SetTitle(s)
	return ac
}

// SetQty sets the "qty" field.
func (ac *ArmamentCreate) SetQty(i int) *ArmamentCreate {
	ac.mutation.SetQty(i)
	return ac
}

// AddSpacecraftIDs adds the "Spacecraft" edge to the Spacecraft entity by IDs.
func (ac *ArmamentCreate) AddSpacecraftIDs(ids ...int) *ArmamentCreate {
	ac.mutation.AddSpacecraftIDs(ids...)
	return ac
}

// AddSpacecraft adds the "Spacecraft" edges to the Spacecraft entity.
func (ac *ArmamentCreate) AddSpacecraft(s ...*Spacecraft) *ArmamentCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ac.AddSpacecraftIDs(ids...)
}

// Mutation returns the ArmamentMutation object of the builder.
func (ac *ArmamentCreate) Mutation() *ArmamentMutation {
	return ac.mutation
}

// Save creates the Armament in the database.
func (ac *ArmamentCreate) Save(ctx context.Context) (*Armament, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ArmamentCreate) SaveX(ctx context.Context) *Armament {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *ArmamentCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *ArmamentCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *ArmamentCreate) check() error {
	if _, ok := ac.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Armament.title"`)}
	}
	if _, ok := ac.mutation.Qty(); !ok {
		return &ValidationError{Name: "qty", err: errors.New(`ent: missing required field "Armament.qty"`)}
	}
	return nil
}

func (ac *ArmamentCreate) sqlSave(ctx context.Context) (*Armament, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *ArmamentCreate) createSpec() (*Armament, *sqlgraph.CreateSpec) {
	var (
		_node = &Armament{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(armament.Table, sqlgraph.NewFieldSpec(armament.FieldID, field.TypeInt))
	)
	if value, ok := ac.mutation.Title(); ok {
		_spec.SetField(armament.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := ac.mutation.Qty(); ok {
		_spec.SetField(armament.FieldQty, field.TypeInt, value)
		_node.Qty = value
	}
	if nodes := ac.mutation.SpacecraftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   armament.SpacecraftTable,
			Columns: armament.SpacecraftPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spacecraft.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ArmamentCreateBulk is the builder for creating many Armament entities in bulk.
type ArmamentCreateBulk struct {
	config
	err      error
	builders []*ArmamentCreate
}

// Save creates the Armament entities in the database.
func (acb *ArmamentCreateBulk) Save(ctx context.Context) ([]*Armament, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Armament, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArmamentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *ArmamentCreateBulk) SaveX(ctx context.Context) []*Armament {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *ArmamentCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *ArmamentCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
