// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spacecraft/ent/armament"
	"spacecraft/ent/spacecraftarmament"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArmamentCreate is the builder for creating a Armament entity.
type ArmamentCreate struct {
	config
	mutation *ArmamentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (ac *ArmamentCreate) SetTitle(s string) *ArmamentCreate {
	ac.mutation.SetTitle(s)
	return ac
}

// AddSpacecraftIDs adds the "spacecrafts" edge to the SpacecraftArmament entity by IDs.
func (ac *ArmamentCreate) AddSpacecraftIDs(ids ...int) *ArmamentCreate {
	ac.mutation.AddSpacecraftIDs(ids...)
	return ac
}

// AddSpacecrafts adds the "spacecrafts" edges to the SpacecraftArmament entity.
func (ac *ArmamentCreate) AddSpacecrafts(s ...*SpacecraftArmament) *ArmamentCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return ac.AddSpacecraftIDs(ids...)
}

// Mutation returns the ArmamentMutation object of the builder.
func (ac *ArmamentCreate) Mutation() *ArmamentMutation {
	return ac.mutation
}

// Save creates the Armament in the database.
func (ac *ArmamentCreate) Save(ctx context.Context) (*Armament, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ArmamentCreate) SaveX(ctx context.Context) *Armament {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *ArmamentCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *ArmamentCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *ArmamentCreate) check() error {
	if _, ok := ac.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Armament.title"`)}
	}
	return nil
}

func (ac *ArmamentCreate) sqlSave(ctx context.Context) (*Armament, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *ArmamentCreate) createSpec() (*Armament, *sqlgraph.CreateSpec) {
	var (
		_node = &Armament{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(armament.Table, sqlgraph.NewFieldSpec(armament.FieldID, field.TypeInt))
	)
	_spec.OnConflict = ac.conflict
	if value, ok := ac.mutation.Title(); ok {
		_spec.SetField(armament.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if nodes := ac.mutation.SpacecraftsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   armament.SpacecraftsTable,
			Columns: []string{armament.SpacecraftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spacecraftarmament.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Armament.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArmamentUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (ac *ArmamentCreate) OnConflict(opts ...sql.ConflictOption) *ArmamentUpsertOne {
	ac.conflict = opts
	return &ArmamentUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Armament.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ac *ArmamentCreate) OnConflictColumns(columns ...string) *ArmamentUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &ArmamentUpsertOne{
		create: ac,
	}
}

type (
	// ArmamentUpsertOne is the builder for "upsert"-ing
	//  one Armament node.
	ArmamentUpsertOne struct {
		create *ArmamentCreate
	}

	// ArmamentUpsert is the "OnConflict" setter.
	ArmamentUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *ArmamentUpsert) SetTitle(v string) *ArmamentUpsert {
	u.Set(armament.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArmamentUpsert) UpdateTitle() *ArmamentUpsert {
	u.SetExcluded(armament.FieldTitle)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Armament.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ArmamentUpsertOne) UpdateNewValues() *ArmamentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Armament.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ArmamentUpsertOne) Ignore() *ArmamentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArmamentUpsertOne) DoNothing() *ArmamentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArmamentCreate.OnConflict
// documentation for more info.
func (u *ArmamentUpsertOne) Update(set func(*ArmamentUpsert)) *ArmamentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArmamentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *ArmamentUpsertOne) SetTitle(v string) *ArmamentUpsertOne {
	return u.Update(func(s *ArmamentUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArmamentUpsertOne) UpdateTitle() *ArmamentUpsertOne {
	return u.Update(func(s *ArmamentUpsert) {
		s.UpdateTitle()
	})
}

// Exec executes the query.
func (u *ArmamentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArmamentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArmamentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArmamentUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArmamentUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArmamentCreateBulk is the builder for creating many Armament entities in bulk.
type ArmamentCreateBulk struct {
	config
	err      error
	builders []*ArmamentCreate
	conflict []sql.ConflictOption
}

// Save creates the Armament entities in the database.
func (acb *ArmamentCreateBulk) Save(ctx context.Context) ([]*Armament, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Armament, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArmamentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *ArmamentCreateBulk) SaveX(ctx context.Context) []*Armament {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *ArmamentCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *ArmamentCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Armament.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArmamentUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (acb *ArmamentCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArmamentUpsertBulk {
	acb.conflict = opts
	return &ArmamentUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Armament.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (acb *ArmamentCreateBulk) OnConflictColumns(columns ...string) *ArmamentUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &ArmamentUpsertBulk{
		create: acb,
	}
}

// ArmamentUpsertBulk is the builder for "upsert"-ing
// a bulk of Armament nodes.
type ArmamentUpsertBulk struct {
	create *ArmamentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Armament.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ArmamentUpsertBulk) UpdateNewValues() *ArmamentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Armament.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ArmamentUpsertBulk) Ignore() *ArmamentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArmamentUpsertBulk) DoNothing() *ArmamentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArmamentCreateBulk.OnConflict
// documentation for more info.
func (u *ArmamentUpsertBulk) Update(set func(*ArmamentUpsert)) *ArmamentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArmamentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *ArmamentUpsertBulk) SetTitle(v string) *ArmamentUpsertBulk {
	return u.Update(func(s *ArmamentUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArmamentUpsertBulk) UpdateTitle() *ArmamentUpsertBulk {
	return u.Update(func(s *ArmamentUpsert) {
		s.UpdateTitle()
	})
}

// Exec executes the query.
func (u *ArmamentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArmamentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArmamentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArmamentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
