// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"spacecraft/ent/armament"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Armament is the model entity for the Armament schema.
type Armament struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArmamentQuery when eager-loading is set.
	Edges        ArmamentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ArmamentEdges holds the relations/edges for other nodes in the graph.
type ArmamentEdges struct {
	// Spacecrafts holds the value of the spacecrafts edge.
	Spacecrafts []*SpacecraftArmament `json:"spacecrafts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SpacecraftsOrErr returns the Spacecrafts value or an error if the edge
// was not loaded in eager-loading.
func (e ArmamentEdges) SpacecraftsOrErr() ([]*SpacecraftArmament, error) {
	if e.loadedTypes[0] {
		return e.Spacecrafts, nil
	}
	return nil, &NotLoadedError{edge: "spacecrafts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Armament) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case armament.FieldID:
			values[i] = new(sql.NullInt64)
		case armament.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Armament fields.
func (a *Armament) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case armament.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case armament.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				a.Title = value.String
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Armament.
// This includes values selected through modifiers, order, etc.
func (a *Armament) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QuerySpacecrafts queries the "spacecrafts" edge of the Armament entity.
func (a *Armament) QuerySpacecrafts() *SpacecraftArmamentQuery {
	return NewArmamentClient(a.config).QuerySpacecrafts(a)
}

// Update returns a builder for updating this Armament.
// Note that you need to call Armament.Unwrap() before calling this method if this Armament
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Armament) Update() *ArmamentUpdateOne {
	return NewArmamentClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Armament entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Armament) Unwrap() *Armament {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Armament is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Armament) String() string {
	var builder strings.Builder
	builder.WriteString("Armament(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("title=")
	builder.WriteString(a.Title)
	builder.WriteByte(')')
	return builder.String()
}

// Armaments is a parsable slice of Armament.
type Armaments []*Armament
