// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"spacecraft/ent/migrate"

	"spacecraft/ent/armament"
	"spacecraft/ent/spacecraft"
	"spacecraft/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Armament is the client for interacting with the Armament builders.
	Armament *ArmamentClient
	// Spacecraft is the client for interacting with the Spacecraft builders.
	Spacecraft *SpacecraftClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Armament = NewArmamentClient(c.config)
	c.Spacecraft = NewSpacecraftClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Armament:   NewArmamentClient(cfg),
		Spacecraft: NewSpacecraftClient(cfg),
		User:       NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Armament:   NewArmamentClient(cfg),
		Spacecraft: NewSpacecraftClient(cfg),
		User:       NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Armament.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Armament.Use(hooks...)
	c.Spacecraft.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Armament.Intercept(interceptors...)
	c.Spacecraft.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ArmamentMutation:
		return c.Armament.mutate(ctx, m)
	case *SpacecraftMutation:
		return c.Spacecraft.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ArmamentClient is a client for the Armament schema.
type ArmamentClient struct {
	config
}

// NewArmamentClient returns a client for the Armament from the given config.
func NewArmamentClient(c config) *ArmamentClient {
	return &ArmamentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `armament.Hooks(f(g(h())))`.
func (c *ArmamentClient) Use(hooks ...Hook) {
	c.hooks.Armament = append(c.hooks.Armament, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `armament.Intercept(f(g(h())))`.
func (c *ArmamentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Armament = append(c.inters.Armament, interceptors...)
}

// Create returns a builder for creating a Armament entity.
func (c *ArmamentClient) Create() *ArmamentCreate {
	mutation := newArmamentMutation(c.config, OpCreate)
	return &ArmamentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Armament entities.
func (c *ArmamentClient) CreateBulk(builders ...*ArmamentCreate) *ArmamentCreateBulk {
	return &ArmamentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArmamentClient) MapCreateBulk(slice any, setFunc func(*ArmamentCreate, int)) *ArmamentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArmamentCreateBulk{err: fmt.Errorf("calling to ArmamentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArmamentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArmamentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Armament.
func (c *ArmamentClient) Update() *ArmamentUpdate {
	mutation := newArmamentMutation(c.config, OpUpdate)
	return &ArmamentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArmamentClient) UpdateOne(a *Armament) *ArmamentUpdateOne {
	mutation := newArmamentMutation(c.config, OpUpdateOne, withArmament(a))
	return &ArmamentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArmamentClient) UpdateOneID(id int) *ArmamentUpdateOne {
	mutation := newArmamentMutation(c.config, OpUpdateOne, withArmamentID(id))
	return &ArmamentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Armament.
func (c *ArmamentClient) Delete() *ArmamentDelete {
	mutation := newArmamentMutation(c.config, OpDelete)
	return &ArmamentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArmamentClient) DeleteOne(a *Armament) *ArmamentDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArmamentClient) DeleteOneID(id int) *ArmamentDeleteOne {
	builder := c.Delete().Where(armament.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArmamentDeleteOne{builder}
}

// Query returns a query builder for Armament.
func (c *ArmamentClient) Query() *ArmamentQuery {
	return &ArmamentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArmament},
		inters: c.Interceptors(),
	}
}

// Get returns a Armament entity by its id.
func (c *ArmamentClient) Get(ctx context.Context, id int) (*Armament, error) {
	return c.Query().Where(armament.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArmamentClient) GetX(ctx context.Context, id int) *Armament {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySpacecraft queries the Spacecraft edge of a Armament.
func (c *ArmamentClient) QuerySpacecraft(a *Armament) *SpacecraftQuery {
	query := (&SpacecraftClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(armament.Table, armament.FieldID, id),
			sqlgraph.To(spacecraft.Table, spacecraft.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, armament.SpacecraftTable, armament.SpacecraftPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ArmamentClient) Hooks() []Hook {
	return c.hooks.Armament
}

// Interceptors returns the client interceptors.
func (c *ArmamentClient) Interceptors() []Interceptor {
	return c.inters.Armament
}

func (c *ArmamentClient) mutate(ctx context.Context, m *ArmamentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArmamentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArmamentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArmamentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArmamentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Armament mutation op: %q", m.Op())
	}
}

// SpacecraftClient is a client for the Spacecraft schema.
type SpacecraftClient struct {
	config
}

// NewSpacecraftClient returns a client for the Spacecraft from the given config.
func NewSpacecraftClient(c config) *SpacecraftClient {
	return &SpacecraftClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `spacecraft.Hooks(f(g(h())))`.
func (c *SpacecraftClient) Use(hooks ...Hook) {
	c.hooks.Spacecraft = append(c.hooks.Spacecraft, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `spacecraft.Intercept(f(g(h())))`.
func (c *SpacecraftClient) Intercept(interceptors ...Interceptor) {
	c.inters.Spacecraft = append(c.inters.Spacecraft, interceptors...)
}

// Create returns a builder for creating a Spacecraft entity.
func (c *SpacecraftClient) Create() *SpacecraftCreate {
	mutation := newSpacecraftMutation(c.config, OpCreate)
	return &SpacecraftCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Spacecraft entities.
func (c *SpacecraftClient) CreateBulk(builders ...*SpacecraftCreate) *SpacecraftCreateBulk {
	return &SpacecraftCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SpacecraftClient) MapCreateBulk(slice any, setFunc func(*SpacecraftCreate, int)) *SpacecraftCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SpacecraftCreateBulk{err: fmt.Errorf("calling to SpacecraftClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SpacecraftCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SpacecraftCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Spacecraft.
func (c *SpacecraftClient) Update() *SpacecraftUpdate {
	mutation := newSpacecraftMutation(c.config, OpUpdate)
	return &SpacecraftUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SpacecraftClient) UpdateOne(s *Spacecraft) *SpacecraftUpdateOne {
	mutation := newSpacecraftMutation(c.config, OpUpdateOne, withSpacecraft(s))
	return &SpacecraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SpacecraftClient) UpdateOneID(id int) *SpacecraftUpdateOne {
	mutation := newSpacecraftMutation(c.config, OpUpdateOne, withSpacecraftID(id))
	return &SpacecraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Spacecraft.
func (c *SpacecraftClient) Delete() *SpacecraftDelete {
	mutation := newSpacecraftMutation(c.config, OpDelete)
	return &SpacecraftDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SpacecraftClient) DeleteOne(s *Spacecraft) *SpacecraftDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SpacecraftClient) DeleteOneID(id int) *SpacecraftDeleteOne {
	builder := c.Delete().Where(spacecraft.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SpacecraftDeleteOne{builder}
}

// Query returns a query builder for Spacecraft.
func (c *SpacecraftClient) Query() *SpacecraftQuery {
	return &SpacecraftQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSpacecraft},
		inters: c.Interceptors(),
	}
}

// Get returns a Spacecraft entity by its id.
func (c *SpacecraftClient) Get(ctx context.Context, id int) (*Spacecraft, error) {
	return c.Query().Where(spacecraft.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SpacecraftClient) GetX(ctx context.Context, id int) *Spacecraft {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryArmaments queries the armaments edge of a Spacecraft.
func (c *SpacecraftClient) QueryArmaments(s *Spacecraft) *ArmamentQuery {
	query := (&ArmamentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(spacecraft.Table, spacecraft.FieldID, id),
			sqlgraph.To(armament.Table, armament.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, spacecraft.ArmamentsTable, spacecraft.ArmamentsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SpacecraftClient) Hooks() []Hook {
	return c.hooks.Spacecraft
}

// Interceptors returns the client interceptors.
func (c *SpacecraftClient) Interceptors() []Interceptor {
	return c.inters.Spacecraft
}

func (c *SpacecraftClient) mutate(ctx context.Context, m *SpacecraftMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SpacecraftCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SpacecraftUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SpacecraftUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SpacecraftDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Spacecraft mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Armament, Spacecraft, User []ent.Hook
	}
	inters struct {
		Armament, Spacecraft, User []ent.Interceptor
	}
)
