// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spacecraft/ent/armament"
	"spacecraft/ent/predicate"
	"spacecraft/ent/spacecraft"
	"spacecraft/ent/user"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeArmament   = "Armament"
	TypeSpacecraft = "Spacecraft"
	TypeUser       = "User"
)

// ArmamentMutation represents an operation that mutates the Armament nodes in the graph.
type ArmamentMutation struct {
	config
	op                 Op
	typ                string
	id                 *int
	title              *string
	qty                *int
	addqty             *int
	clearedFields      map[string]struct{}
	_Spacecraft        map[int]struct{}
	removed_Spacecraft map[int]struct{}
	cleared_Spacecraft bool
	done               bool
	oldValue           func(context.Context) (*Armament, error)
	predicates         []predicate.Armament
}

var _ ent.Mutation = (*ArmamentMutation)(nil)

// armamentOption allows management of the mutation configuration using functional options.
type armamentOption func(*ArmamentMutation)

// newArmamentMutation creates new mutation for the Armament entity.
func newArmamentMutation(c config, op Op, opts ...armamentOption) *ArmamentMutation {
	m := &ArmamentMutation{
		config:        c,
		op:            op,
		typ:           TypeArmament,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withArmamentID sets the ID field of the mutation.
func withArmamentID(id int) armamentOption {
	return func(m *ArmamentMutation) {
		var (
			err   error
			once  sync.Once
			value *Armament
		)
		m.oldValue = func(ctx context.Context) (*Armament, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Armament.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withArmament sets the old Armament of the mutation.
func withArmament(node *Armament) armamentOption {
	return func(m *ArmamentMutation) {
		m.oldValue = func(context.Context) (*Armament, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ArmamentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ArmamentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ArmamentMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ArmamentMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Armament.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTitle sets the "title" field.
func (m *ArmamentMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ArmamentMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Armament entity.
// If the Armament object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ArmamentMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ArmamentMutation) ResetTitle() {
	m.title = nil
}

// SetQty sets the "qty" field.
func (m *ArmamentMutation) SetQty(i int) {
	m.qty = &i
	m.addqty = nil
}

// Qty returns the value of the "qty" field in the mutation.
func (m *ArmamentMutation) Qty() (r int, exists bool) {
	v := m.qty
	if v == nil {
		return
	}
	return *v, true
}

// OldQty returns the old "qty" field's value of the Armament entity.
// If the Armament object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ArmamentMutation) OldQty(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldQty is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldQty requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldQty: %w", err)
	}
	return oldValue.Qty, nil
}

// AddQty adds i to the "qty" field.
func (m *ArmamentMutation) AddQty(i int) {
	if m.addqty != nil {
		*m.addqty += i
	} else {
		m.addqty = &i
	}
}

// AddedQty returns the value that was added to the "qty" field in this mutation.
func (m *ArmamentMutation) AddedQty() (r int, exists bool) {
	v := m.addqty
	if v == nil {
		return
	}
	return *v, true
}

// ResetQty resets all changes to the "qty" field.
func (m *ArmamentMutation) ResetQty() {
	m.qty = nil
	m.addqty = nil
}

// AddSpacecraftIDs adds the "Spacecraft" edge to the Spacecraft entity by ids.
func (m *ArmamentMutation) AddSpacecraftIDs(ids ...int) {
	if m._Spacecraft == nil {
		m._Spacecraft = make(map[int]struct{})
	}
	for i := range ids {
		m._Spacecraft[ids[i]] = struct{}{}
	}
}

// ClearSpacecraft clears the "Spacecraft" edge to the Spacecraft entity.
func (m *ArmamentMutation) ClearSpacecraft() {
	m.cleared_Spacecraft = true
}

// SpacecraftCleared reports if the "Spacecraft" edge to the Spacecraft entity was cleared.
func (m *ArmamentMutation) SpacecraftCleared() bool {
	return m.cleared_Spacecraft
}

// RemoveSpacecraftIDs removes the "Spacecraft" edge to the Spacecraft entity by IDs.
func (m *ArmamentMutation) RemoveSpacecraftIDs(ids ...int) {
	if m.removed_Spacecraft == nil {
		m.removed_Spacecraft = make(map[int]struct{})
	}
	for i := range ids {
		delete(m._Spacecraft, ids[i])
		m.removed_Spacecraft[ids[i]] = struct{}{}
	}
}

// RemovedSpacecraft returns the removed IDs of the "Spacecraft" edge to the Spacecraft entity.
func (m *ArmamentMutation) RemovedSpacecraftIDs() (ids []int) {
	for id := range m.removed_Spacecraft {
		ids = append(ids, id)
	}
	return
}

// SpacecraftIDs returns the "Spacecraft" edge IDs in the mutation.
func (m *ArmamentMutation) SpacecraftIDs() (ids []int) {
	for id := range m._Spacecraft {
		ids = append(ids, id)
	}
	return
}

// ResetSpacecraft resets all changes to the "Spacecraft" edge.
func (m *ArmamentMutation) ResetSpacecraft() {
	m._Spacecraft = nil
	m.cleared_Spacecraft = false
	m.removed_Spacecraft = nil
}

// Where appends a list predicates to the ArmamentMutation builder.
func (m *ArmamentMutation) Where(ps ...predicate.Armament) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ArmamentMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ArmamentMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Armament, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ArmamentMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ArmamentMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Armament).
func (m *ArmamentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ArmamentMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.title != nil {
		fields = append(fields, armament.FieldTitle)
	}
	if m.qty != nil {
		fields = append(fields, armament.FieldQty)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ArmamentMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case armament.FieldTitle:
		return m.Title()
	case armament.FieldQty:
		return m.Qty()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ArmamentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case armament.FieldTitle:
		return m.OldTitle(ctx)
	case armament.FieldQty:
		return m.OldQty(ctx)
	}
	return nil, fmt.Errorf("unknown Armament field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ArmamentMutation) SetField(name string, value ent.Value) error {
	switch name {
	case armament.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case armament.FieldQty:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetQty(v)
		return nil
	}
	return fmt.Errorf("unknown Armament field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ArmamentMutation) AddedFields() []string {
	var fields []string
	if m.addqty != nil {
		fields = append(fields, armament.FieldQty)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ArmamentMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case armament.FieldQty:
		return m.AddedQty()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ArmamentMutation) AddField(name string, value ent.Value) error {
	switch name {
	case armament.FieldQty:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddQty(v)
		return nil
	}
	return fmt.Errorf("unknown Armament numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ArmamentMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ArmamentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ArmamentMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Armament nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ArmamentMutation) ResetField(name string) error {
	switch name {
	case armament.FieldTitle:
		m.ResetTitle()
		return nil
	case armament.FieldQty:
		m.ResetQty()
		return nil
	}
	return fmt.Errorf("unknown Armament field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ArmamentMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m._Spacecraft != nil {
		edges = append(edges, armament.EdgeSpacecraft)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ArmamentMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case armament.EdgeSpacecraft:
		ids := make([]ent.Value, 0, len(m._Spacecraft))
		for id := range m._Spacecraft {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ArmamentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removed_Spacecraft != nil {
		edges = append(edges, armament.EdgeSpacecraft)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ArmamentMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case armament.EdgeSpacecraft:
		ids := make([]ent.Value, 0, len(m.removed_Spacecraft))
		for id := range m.removed_Spacecraft {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ArmamentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleared_Spacecraft {
		edges = append(edges, armament.EdgeSpacecraft)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ArmamentMutation) EdgeCleared(name string) bool {
	switch name {
	case armament.EdgeSpacecraft:
		return m.cleared_Spacecraft
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ArmamentMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Armament unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ArmamentMutation) ResetEdge(name string) error {
	switch name {
	case armament.EdgeSpacecraft:
		m.ResetSpacecraft()
		return nil
	}
	return fmt.Errorf("unknown Armament edge %s", name)
}

// SpacecraftMutation represents an operation that mutates the Spacecraft nodes in the graph.
type SpacecraftMutation struct {
	config
	op               Op
	typ              string
	id               *int
	name             *string
	class            *string
	crew             *int
	addcrew          *int
	image            *string
	value            *float64
	addvalue         *float64
	status           *string
	clearedFields    map[string]struct{}
	armaments        map[int]struct{}
	removedarmaments map[int]struct{}
	clearedarmaments bool
	done             bool
	oldValue         func(context.Context) (*Spacecraft, error)
	predicates       []predicate.Spacecraft
}

var _ ent.Mutation = (*SpacecraftMutation)(nil)

// spacecraftOption allows management of the mutation configuration using functional options.
type spacecraftOption func(*SpacecraftMutation)

// newSpacecraftMutation creates new mutation for the Spacecraft entity.
func newSpacecraftMutation(c config, op Op, opts ...spacecraftOption) *SpacecraftMutation {
	m := &SpacecraftMutation{
		config:        c,
		op:            op,
		typ:           TypeSpacecraft,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSpacecraftID sets the ID field of the mutation.
func withSpacecraftID(id int) spacecraftOption {
	return func(m *SpacecraftMutation) {
		var (
			err   error
			once  sync.Once
			value *Spacecraft
		)
		m.oldValue = func(ctx context.Context) (*Spacecraft, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Spacecraft.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSpacecraft sets the old Spacecraft of the mutation.
func withSpacecraft(node *Spacecraft) spacecraftOption {
	return func(m *SpacecraftMutation) {
		m.oldValue = func(context.Context) (*Spacecraft, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SpacecraftMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SpacecraftMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SpacecraftMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SpacecraftMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Spacecraft.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *SpacecraftMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SpacecraftMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SpacecraftMutation) ResetName() {
	m.name = nil
}

// SetClass sets the "class" field.
func (m *SpacecraftMutation) SetClass(s string) {
	m.class = &s
}

// Class returns the value of the "class" field in the mutation.
func (m *SpacecraftMutation) Class() (r string, exists bool) {
	v := m.class
	if v == nil {
		return
	}
	return *v, true
}

// OldClass returns the old "class" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldClass(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClass is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClass requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClass: %w", err)
	}
	return oldValue.Class, nil
}

// ResetClass resets all changes to the "class" field.
func (m *SpacecraftMutation) ResetClass() {
	m.class = nil
}

// SetCrew sets the "crew" field.
func (m *SpacecraftMutation) SetCrew(i int) {
	m.crew = &i
	m.addcrew = nil
}

// Crew returns the value of the "crew" field in the mutation.
func (m *SpacecraftMutation) Crew() (r int, exists bool) {
	v := m.crew
	if v == nil {
		return
	}
	return *v, true
}

// OldCrew returns the old "crew" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldCrew(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCrew is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCrew requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCrew: %w", err)
	}
	return oldValue.Crew, nil
}

// AddCrew adds i to the "crew" field.
func (m *SpacecraftMutation) AddCrew(i int) {
	if m.addcrew != nil {
		*m.addcrew += i
	} else {
		m.addcrew = &i
	}
}

// AddedCrew returns the value that was added to the "crew" field in this mutation.
func (m *SpacecraftMutation) AddedCrew() (r int, exists bool) {
	v := m.addcrew
	if v == nil {
		return
	}
	return *v, true
}

// ResetCrew resets all changes to the "crew" field.
func (m *SpacecraftMutation) ResetCrew() {
	m.crew = nil
	m.addcrew = nil
}

// SetImage sets the "image" field.
func (m *SpacecraftMutation) SetImage(s string) {
	m.image = &s
}

// Image returns the value of the "image" field in the mutation.
func (m *SpacecraftMutation) Image() (r string, exists bool) {
	v := m.image
	if v == nil {
		return
	}
	return *v, true
}

// OldImage returns the old "image" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImage: %w", err)
	}
	return oldValue.Image, nil
}

// ResetImage resets all changes to the "image" field.
func (m *SpacecraftMutation) ResetImage() {
	m.image = nil
}

// SetValue sets the "value" field.
func (m *SpacecraftMutation) SetValue(f float64) {
	m.value = &f
	m.addvalue = nil
}

// Value returns the value of the "value" field in the mutation.
func (m *SpacecraftMutation) Value() (r float64, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// AddValue adds f to the "value" field.
func (m *SpacecraftMutation) AddValue(f float64) {
	if m.addvalue != nil {
		*m.addvalue += f
	} else {
		m.addvalue = &f
	}
}

// AddedValue returns the value that was added to the "value" field in this mutation.
func (m *SpacecraftMutation) AddedValue() (r float64, exists bool) {
	v := m.addvalue
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue resets all changes to the "value" field.
func (m *SpacecraftMutation) ResetValue() {
	m.value = nil
	m.addvalue = nil
}

// SetStatus sets the "status" field.
func (m *SpacecraftMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *SpacecraftMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Spacecraft entity.
// If the Spacecraft object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SpacecraftMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *SpacecraftMutation) ResetStatus() {
	m.status = nil
}

// AddArmamentIDs adds the "armaments" edge to the Armament entity by ids.
func (m *SpacecraftMutation) AddArmamentIDs(ids ...int) {
	if m.armaments == nil {
		m.armaments = make(map[int]struct{})
	}
	for i := range ids {
		m.armaments[ids[i]] = struct{}{}
	}
}

// ClearArmaments clears the "armaments" edge to the Armament entity.
func (m *SpacecraftMutation) ClearArmaments() {
	m.clearedarmaments = true
}

// ArmamentsCleared reports if the "armaments" edge to the Armament entity was cleared.
func (m *SpacecraftMutation) ArmamentsCleared() bool {
	return m.clearedarmaments
}

// RemoveArmamentIDs removes the "armaments" edge to the Armament entity by IDs.
func (m *SpacecraftMutation) RemoveArmamentIDs(ids ...int) {
	if m.removedarmaments == nil {
		m.removedarmaments = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.armaments, ids[i])
		m.removedarmaments[ids[i]] = struct{}{}
	}
}

// RemovedArmaments returns the removed IDs of the "armaments" edge to the Armament entity.
func (m *SpacecraftMutation) RemovedArmamentsIDs() (ids []int) {
	for id := range m.removedarmaments {
		ids = append(ids, id)
	}
	return
}

// ArmamentsIDs returns the "armaments" edge IDs in the mutation.
func (m *SpacecraftMutation) ArmamentsIDs() (ids []int) {
	for id := range m.armaments {
		ids = append(ids, id)
	}
	return
}

// ResetArmaments resets all changes to the "armaments" edge.
func (m *SpacecraftMutation) ResetArmaments() {
	m.armaments = nil
	m.clearedarmaments = false
	m.removedarmaments = nil
}

// Where appends a list predicates to the SpacecraftMutation builder.
func (m *SpacecraftMutation) Where(ps ...predicate.Spacecraft) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SpacecraftMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SpacecraftMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Spacecraft, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SpacecraftMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SpacecraftMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Spacecraft).
func (m *SpacecraftMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SpacecraftMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.name != nil {
		fields = append(fields, spacecraft.FieldName)
	}
	if m.class != nil {
		fields = append(fields, spacecraft.FieldClass)
	}
	if m.crew != nil {
		fields = append(fields, spacecraft.FieldCrew)
	}
	if m.image != nil {
		fields = append(fields, spacecraft.FieldImage)
	}
	if m.value != nil {
		fields = append(fields, spacecraft.FieldValue)
	}
	if m.status != nil {
		fields = append(fields, spacecraft.FieldStatus)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SpacecraftMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case spacecraft.FieldName:
		return m.Name()
	case spacecraft.FieldClass:
		return m.Class()
	case spacecraft.FieldCrew:
		return m.Crew()
	case spacecraft.FieldImage:
		return m.Image()
	case spacecraft.FieldValue:
		return m.Value()
	case spacecraft.FieldStatus:
		return m.Status()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SpacecraftMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case spacecraft.FieldName:
		return m.OldName(ctx)
	case spacecraft.FieldClass:
		return m.OldClass(ctx)
	case spacecraft.FieldCrew:
		return m.OldCrew(ctx)
	case spacecraft.FieldImage:
		return m.OldImage(ctx)
	case spacecraft.FieldValue:
		return m.OldValue(ctx)
	case spacecraft.FieldStatus:
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown Spacecraft field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SpacecraftMutation) SetField(name string, value ent.Value) error {
	switch name {
	case spacecraft.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case spacecraft.FieldClass:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClass(v)
		return nil
	case spacecraft.FieldCrew:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCrew(v)
		return nil
	case spacecraft.FieldImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImage(v)
		return nil
	case spacecraft.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	case spacecraft.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	}
	return fmt.Errorf("unknown Spacecraft field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SpacecraftMutation) AddedFields() []string {
	var fields []string
	if m.addcrew != nil {
		fields = append(fields, spacecraft.FieldCrew)
	}
	if m.addvalue != nil {
		fields = append(fields, spacecraft.FieldValue)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SpacecraftMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case spacecraft.FieldCrew:
		return m.AddedCrew()
	case spacecraft.FieldValue:
		return m.AddedValue()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SpacecraftMutation) AddField(name string, value ent.Value) error {
	switch name {
	case spacecraft.FieldCrew:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCrew(v)
		return nil
	case spacecraft.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValue(v)
		return nil
	}
	return fmt.Errorf("unknown Spacecraft numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SpacecraftMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SpacecraftMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SpacecraftMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Spacecraft nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SpacecraftMutation) ResetField(name string) error {
	switch name {
	case spacecraft.FieldName:
		m.ResetName()
		return nil
	case spacecraft.FieldClass:
		m.ResetClass()
		return nil
	case spacecraft.FieldCrew:
		m.ResetCrew()
		return nil
	case spacecraft.FieldImage:
		m.ResetImage()
		return nil
	case spacecraft.FieldValue:
		m.ResetValue()
		return nil
	case spacecraft.FieldStatus:
		m.ResetStatus()
		return nil
	}
	return fmt.Errorf("unknown Spacecraft field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SpacecraftMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.armaments != nil {
		edges = append(edges, spacecraft.EdgeArmaments)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SpacecraftMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case spacecraft.EdgeArmaments:
		ids := make([]ent.Value, 0, len(m.armaments))
		for id := range m.armaments {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SpacecraftMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedarmaments != nil {
		edges = append(edges, spacecraft.EdgeArmaments)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SpacecraftMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case spacecraft.EdgeArmaments:
		ids := make([]ent.Value, 0, len(m.removedarmaments))
		for id := range m.removedarmaments {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SpacecraftMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedarmaments {
		edges = append(edges, spacecraft.EdgeArmaments)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SpacecraftMutation) EdgeCleared(name string) bool {
	switch name {
	case spacecraft.EdgeArmaments:
		return m.clearedarmaments
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SpacecraftMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Spacecraft unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SpacecraftMutation) ResetEdge(name string) error {
	switch name {
	case spacecraft.EdgeArmaments:
		m.ResetArmaments()
		return nil
	}
	return fmt.Errorf("unknown Spacecraft edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	username      *string
	password      *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*User, error)
	predicates    []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUsername sets the "username" field.
func (m *UserMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *UserMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *UserMutation) ResetUsername() {
	m.username = nil
}

// SetPassword sets the "password" field.
func (m *UserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *UserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.username != nil {
		fields = append(fields, user.FieldUsername)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldUsername:
		return m.Username()
	case user.FieldPassword:
		return m.Password()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldUsername:
		return m.OldUsername(ctx)
	case user.FieldPassword:
		return m.OldPassword(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldUsername:
		m.ResetUsername()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown User edge %s", name)
}
