// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"spacecraft/ent/predicate"
	"spacecraft/ent/spacecraft"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpacecraftDelete is the builder for deleting a Spacecraft entity.
type SpacecraftDelete struct {
	config
	hooks    []Hook
	mutation *SpacecraftMutation
}

// Where appends a list predicates to the SpacecraftDelete builder.
func (sd *SpacecraftDelete) Where(ps ...predicate.Spacecraft) *SpacecraftDelete {
	sd.mutation.Where(ps...)
	return sd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sd *SpacecraftDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sd.sqlExec, sd.mutation, sd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sd *SpacecraftDelete) ExecX(ctx context.Context) int {
	n, err := sd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sd *SpacecraftDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(spacecraft.Table, sqlgraph.NewFieldSpec(spacecraft.FieldID, field.TypeInt))
	if ps := sd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sd.mutation.done = true
	return affected, err
}

// SpacecraftDeleteOne is the builder for deleting a single Spacecraft entity.
type SpacecraftDeleteOne struct {
	sd *SpacecraftDelete
}

// Where appends a list predicates to the SpacecraftDelete builder.
func (sdo *SpacecraftDeleteOne) Where(ps ...predicate.Spacecraft) *SpacecraftDeleteOne {
	sdo.sd.mutation.Where(ps...)
	return sdo
}

// Exec executes the deletion query.
func (sdo *SpacecraftDeleteOne) Exec(ctx context.Context) error {
	n, err := sdo.sd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{spacecraft.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sdo *SpacecraftDeleteOne) ExecX(ctx context.Context) {
	if err := sdo.Exec(ctx); err != nil {
		panic(err)
	}
}
