// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"spacecraft/ent/predicate"
	"spacecraft/ent/spacecraftarmament"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpacecraftArmamentDelete is the builder for deleting a SpacecraftArmament entity.
type SpacecraftArmamentDelete struct {
	config
	hooks    []Hook
	mutation *SpacecraftArmamentMutation
}

// Where appends a list predicates to the SpacecraftArmamentDelete builder.
func (sad *SpacecraftArmamentDelete) Where(ps ...predicate.SpacecraftArmament) *SpacecraftArmamentDelete {
	sad.mutation.Where(ps...)
	return sad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sad *SpacecraftArmamentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sad.sqlExec, sad.mutation, sad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sad *SpacecraftArmamentDelete) ExecX(ctx context.Context) int {
	n, err := sad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sad *SpacecraftArmamentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(spacecraftarmament.Table, sqlgraph.NewFieldSpec(spacecraftarmament.FieldID, field.TypeInt))
	if ps := sad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sad.mutation.done = true
	return affected, err
}

// SpacecraftArmamentDeleteOne is the builder for deleting a single SpacecraftArmament entity.
type SpacecraftArmamentDeleteOne struct {
	sad *SpacecraftArmamentDelete
}

// Where appends a list predicates to the SpacecraftArmamentDelete builder.
func (sado *SpacecraftArmamentDeleteOne) Where(ps ...predicate.SpacecraftArmament) *SpacecraftArmamentDeleteOne {
	sado.sad.mutation.Where(ps...)
	return sado
}

// Exec executes the deletion query.
func (sado *SpacecraftArmamentDeleteOne) Exec(ctx context.Context) error {
	n, err := sado.sad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{spacecraftarmament.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sado *SpacecraftArmamentDeleteOne) ExecX(ctx context.Context) {
	if err := sado.Exec(ctx); err != nil {
		panic(err)
	}
}
