// Code generated by ent, DO NOT EDIT.

package armament

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the armament type in the database.
	Label = "armament"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// EdgeSpacecrafts holds the string denoting the spacecrafts edge name in mutations.
	EdgeSpacecrafts = "spacecrafts"
	// Table holds the table name of the armament in the database.
	Table = "armaments"
	// SpacecraftsTable is the table that holds the spacecrafts relation/edge.
	SpacecraftsTable = "spacecraft_armaments"
	// SpacecraftsInverseTable is the table name for the SpacecraftArmament entity.
	// It exists in this package in order to avoid circular dependency with the "spacecraftarmament" package.
	SpacecraftsInverseTable = "spacecraft_armaments"
	// SpacecraftsColumn is the table column denoting the spacecrafts relation/edge.
	SpacecraftsColumn = "armament_id"
)

// Columns holds all SQL columns for armament fields.
var Columns = []string{
	FieldID,
	FieldTitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Armament queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySpacecraftsCount orders the results by spacecrafts count.
func BySpacecraftsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSpacecraftsStep(), opts...)
	}
}

// BySpacecrafts orders the results by spacecrafts terms.
func BySpacecrafts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSpacecraftsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSpacecraftsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SpacecraftsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SpacecraftsTable, SpacecraftsColumn),
	)
}
