// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Armament is the predicate function for armament builders.
type Armament func(*sql.Selector)

// Spacecraft is the predicate function for spacecraft builders.
type Spacecraft func(*sql.Selector)

// SpacecraftArmament is the predicate function for spacecraftarmament builders.
type SpacecraftArmament func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
